title: <p align="center">Khyati Desai Portfolio</p>
logo: /assets/img/logo.png
description: Currently studying ML & AI from IIIT Bangalore with upGrad.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
