title: <p align="center">Khyati Desai</p>
logo: /assets/img/logo.png
description: Data Analysis, Machine Learning, Python, Software Engineering
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
